# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
      - id: prettier
        name: prettier-ts
        args: ['--parser', 'typescript']
        files: ^frontend/.*\.ts$
      
      - id: prettier
        name: prettier-tsx
        args: ['--parser', 'typescript']
        files: ^frontend/.*\.tsx$

      - id: prettier
        name: prettier-html
        files: '\.(html)$'
        args: ['--parser', 'html']

  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
        files: ^backend/.*\.py$

  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
      files: ^backend/.*\.py$
 
