# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
      - id: prettier
        files: '\.(ts|tsx|js|jsx|json|html|css|scss)$'
        exclude: '\.gen.ts$'

  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
        files: ^backend/.*\.py$

  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
      files: ^backend/.*\.py$
 
