# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.2.1'
    hooks:
      - id: prettier
        files: ^frontend/.*

  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
        files: ^backend/.*
        
  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
      files: ^backend/.*
 
