repos:
  - repo: https://github.com/prettier/prettier
    rev: 2.2.1
    hooks:
      - id: prettier
        files: ^frontend/.*

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake --in-place --remove-all-unused-imports --remove-unused-variables
        language: python
        types: [python]
        files: ^backend/.*

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        files: ^backend/.*