/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as LogsImport } from './routes/logs'
import { Route as DevicesImport } from './routes/devices'
import { Route as DataExplorerImport } from './routes/data-explorer'
import { Route as DashboardImport } from './routes/dashboard'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const LogsRoute = LogsImport.update({
  path: '/logs',
  getParentRoute: () => rootRoute,
} as any)

const DevicesRoute = DevicesImport.update({
  path: '/devices',
  getParentRoute: () => rootRoute,
} as any)

const DataExplorerRoute = DataExplorerImport.update({
  path: '/data-explorer',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/data-explorer': {
      id: '/data-explorer'
      path: '/data-explorer'
      fullPath: '/data-explorer'
      preLoaderRoute: typeof DataExplorerImport
      parentRoute: typeof rootRoute
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesImport
      parentRoute: typeof rootRoute
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  DashboardRoute,
  DataExplorerRoute,
  DevicesRoute,
  LogsRoute,
  SettingsRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/dashboard",
        "/data-explorer",
        "/devices",
        "/logs",
        "/settings"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/data-explorer": {
      "filePath": "data-explorer.tsx"
    },
    "/devices": {
      "filePath": "devices.tsx"
    },
    "/logs": {
      "filePath": "logs.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
