/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as SchedulerImport } from './routes/scheduler'
import { Route as LogsImport } from './routes/logs'
import { Route as LoginImport } from './routes/login'
import { Route as DevicesImport } from './routes/devices'
import { Route as DataExplorerImport } from './routes/data-explorer'
import { Route as DashboardImport } from './routes/dashboard'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const SchedulerRoute = SchedulerImport.update({
  path: '/scheduler',
  getParentRoute: () => rootRoute,
} as any)

const LogsRoute = LogsImport.update({
  path: '/logs',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DevicesRoute = DevicesImport.update({
  path: '/devices',
  getParentRoute: () => rootRoute,
} as any)

const DataExplorerRoute = DataExplorerImport.update({
  path: '/data-explorer',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/data-explorer': {
      id: '/data-explorer'
      path: '/data-explorer'
      fullPath: '/data-explorer'
      preLoaderRoute: typeof DataExplorerImport
      parentRoute: typeof rootRoute
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsImport
      parentRoute: typeof rootRoute
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRoute
  '/data-explorer': typeof DataExplorerRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
}

export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/data-explorer': typeof DataExplorerRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/dashboard': typeof DashboardRoute
  '/data-explorer': typeof DataExplorerRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/data-explorer'
    | '/devices'
    | '/login'
    | '/logs'
    | '/scheduler'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/data-explorer'
    | '/devices'
    | '/login'
    | '/logs'
    | '/scheduler'
    | '/settings'
  id:
    | '__root__'
    | '/dashboard'
    | '/data-explorer'
    | '/devices'
    | '/login'
    | '/logs'
    | '/scheduler'
    | '/settings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRoute
  DataExplorerRoute: typeof DataExplorerRoute
  DevicesRoute: typeof DevicesRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  SchedulerRoute: typeof SchedulerRoute
  SettingsRoute: typeof SettingsRoute
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRoute,
  DataExplorerRoute: DataExplorerRoute,
  DevicesRoute: DevicesRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  SchedulerRoute: SchedulerRoute,
  SettingsRoute: SettingsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/dashboard",
        "/data-explorer",
        "/devices",
        "/login",
        "/logs",
        "/scheduler",
        "/settings"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/data-explorer": {
      "filePath": "data-explorer.tsx"
    },
    "/devices": {
      "filePath": "devices.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logs": {
      "filePath": "logs.tsx"
    },
    "/scheduler": {
      "filePath": "scheduler.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
